### ISSUE TITLE
Jest 27: jest is not defined

### ISSUE THREAD

**Issue by ThisIsMissEm** [bpedersen/jest-mock-console#32]
```
ReferenceError: jest is not defined

      118 |       };
      119 |
    > 120 |       const restoreConsole = mockConsole("error");
          |                                         ^
      121 | ...

      at mockConsole (../../node_modules/jest-mock-console/dist/index.js:26:31)
```

I'm using these potentially relevant dependencies:

```
    "jest": "^27.4.3",
    "jest-mock-console": "^1.2.3",
    "ts-jest": "^27.0.7",
```

Looking at `dist/index.js` is does appear that you're not importing jest from `@jest/globals` which was a breaking change in Jest 26: https://jestjs.io/blog/2020/05/05/jest-26#a-new-way-to-consume-jest---jestglobals

I'm also running with the `injectGlobals: false,` setting in `jest.config.js`, setting it to `true` fixes this error

**Comment by bpedersen** [comment]
Thank you for bringing this to my attention. 

This does have to do with the way this package modifies the globals. It could be possible to create a package to modify the expect, test, describe, beforeEach functions that you use instead of `@jest/globals`, but you would need to remember to use it instead of `@jest/globals`, so for now I will add a section to the readme about the `injectGlobals: false` issues that will arise.

**Comment by ThisIsMissEm** [comment]
Another solution could be to accept a `jest` value into `mockConsole`, so `mockConsole("error", jest)` which would then do the right stuff? I'm not sure if that makes sense, but maybe it could work?

**Comment by bpedersen** [comment]
I see. You are talking about using the mockConsole without the setupFile. This is something that should be able to be handled without additional arguments to mockConsole. I have pushed a version 2.0.0 that will directly import from `@jest/globals` for the jest.fn within the mockConsole function. Please test and open an issue if this is not working for you.
